import { Pin } from '../types';

export const pins: Pin[] = [
  // 일본
  {
    id: 1,
    categoryId: 1,
    title: '스시엔 (일본식)',
    latitude: 37.5665,
    longitude: 126.978,
    description: '신선한 스시와 일본 전통 요리를 맛볼 수 있는 곳',
    imageUrl: 'https://example.com/sushi.jpg',
    locationName: '서울 중구 명동',
  },
  {
    id: 2,
    categoryId: 1,
    title: '긴자 라멘',
    latitude: 37.5651,
    longitude: 126.982,
    description: '진한 돈코츠 라멘 전문점',
    imageUrl: '',
    locationName: '서울 중구 을지로',
  },

  // 산
  {
    id: 3,
    categoryId: 2,
    title: '남산공원 전망대',
    latitude: 37.5512,
    longitude: 126.9882,
    description: '서울 전경을 한눈에 볼 수 있는 전망대',
    imageUrl: 'https://example.com/namsan.jpg',
    locationName: '서울 용산구 남산',
  },
  {
    id: 4,
    categoryId: 2,
    title: '북한산 둘레길 입구',
    latitude: 37.6584,
    longitude: 126.977,
    description: '등산과 트레킹을 즐길 수 있는 북한산 입구',
    imageUrl: '',
    locationName: '서울 강북구 북한산로',
  },

  // 맛집
  {
    id: 5,
    categoryId: 3,
    title: '광장시장 빈대떡 골목',
    latitude: 37.5703,
    longitude: 126.9959,
    description: '전통시장에서 즐기는 바삭한 빈대떡',
    imageUrl: 'https://example.com/bindaetteok.jpg',
    locationName: '서울 종로구 창경궁로',
  },
  {
    id: 6,
    categoryId: 3,
    title: '을지로 골뱅이집',
    latitude: 37.5669,
    longitude: 126.9929,
    description: '야들야들한 골뱅이와 맥주 한 잔',
    imageUrl: '',
    locationName: '서울 중구 을지로3가',
  },
  {
    id: 7,
    categoryId: 3,
    title: '이태원 소고기 숯불구이',
    latitude: 37.5349,
    longitude: 126.994,
    description: '숯불 향 가득한 소고기 전문점',
    imageUrl: 'https://example.com/beef.jpg',
    locationName: '서울 용산구 이태원동',
  },
  {
    id: 8,
    categoryId: 3,
    title: '마포 족발골목',
    latitude: 37.5615,
    longitude: 126.908,
    description: '쫄깃한 족발과 보쌈을 즐길 수 있는 거리',
    imageUrl: '',
    locationName: '서울 마포구 공덕동',
  },

  // 카페
  {
    id: 9,
    categoryId: 4,
    title: '북촌 카페거리',
    latitude: 37.5828,
    longitude: 126.986,
    description: '한옥과 어우러진 감성 카페 거리',
    imageUrl: 'https://example.com/bukchon.jpg',
    locationName: '서울 종로구 계동',
  },
  {
    id: 10,
    categoryId: 4,
    title: '성수동 카페거리',
    latitude: 37.5446,
    longitude: 127.0555,
    description: '트렌디한 카페들이 모여 있는 힙한 거리',
    imageUrl: '',
    locationName: '서울 성동구 성수동',
  },
  {
    id: 11,
    categoryId: 4,
    title: '연남동 카페 골목',
    latitude: 37.565,
    longitude: 126.923,
    description: '감각적인 카페들이 가득한 골목',
    imageUrl: 'https://example.com/yeonnam.jpg',
    locationName: '서울 마포구 연남동',
  },
  {
    id: 12,
    categoryId: 4,
    title: '가로수길 티룸',
    latitude: 37.517,
    longitude: 127.021,
    description: '차와 디저트를 즐길 수 있는 티룸',
    imageUrl: '',
    locationName: '서울 강남구 신사동',
  },

  // 편의점
  {
    id: 13,
    categoryId: 5,
    title: '종로 1가 편의점',
    latitude: 37.57,
    longitude: 126.983,
    description: '도심 한복판에서 간단히 들를 수 있는 편의점',
    imageUrl: '',
    locationName: '서울 종로구 종로1가',
  },
  {
    id: 14,
    categoryId: 5,
    title: '강남역 편의점',
    latitude: 37.4979,
    longitude: 127.0276,
    description: '강남역 인근의 편리한 편의점',
    imageUrl: '',
    locationName: '서울 강남구 역삼동',
  },
  {
    id: 15,
    categoryId: 5,
    title: '홍대입구 역 앞 편의점',
    latitude: 37.5577,
    longitude: 126.925,
    description: '홍대입구역 근처 24시 편의점',
    imageUrl: '',
    locationName: '서울 마포구 동교동',
  },
  {
    id: 16,
    categoryId: 5,
    title: '압구정 편의점',
    latitude: 37.5267,
    longitude: 127.028,
    description: '압구정 로데오 근처 편의점',
    imageUrl: '',
    locationName: '서울 강남구 압구정동',
  },

  // 혼합 또는 추가 포인트
  {
    id: 17,
    categoryId: 3,
    title: '명동 떡볶이 거리',
    latitude: 37.56,
    longitude: 126.986,
    description: '명동에서 즐기는 길거리 떡볶이',
    imageUrl: 'https://example.com/tteokbokki.jpg',
    locationName: '서울 중구 명동',
  },
  {
    id: 18,
    categoryId: 4,
    title: '서울숲 근처 카페',
    latitude: 37.5448,
    longitude: 127.0376,
    description: '서울숲을 바라보며 커피 한잔',
    imageUrl: '',
    locationName: '서울 성동구 성수동',
  },
  {
    id: 19,
    categoryId: 3,
    title: '청계천 길거리 음식',
    latitude: 37.5682,
    longitude: 126.9769,
    description: '청계천에서 즐기는 다양한 길거리 간식',
    imageUrl: '',
    locationName: '서울 종로구 청계천로',
  },
  {
    id: 20,
    categoryId: 1,
    title: '일식 덮밥 전문점',
    latitude: 37.5655,
    longitude: 126.975,
    description: '다양한 덮밥 메뉴를 즐길 수 있는 일식집',
    imageUrl: 'https://example.com/donburi.jpg',
    locationName: '서울 중구 소공동',
  },
];
